site_name: github-graphql-client
site_description: GraphQL client in python.

theme:
    name: 'material'
    palette:
      primary: 'light blue'
      accent: 'light blue'
    analytics:
      gtag: 275257853

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

repo_name: denisart/github-graphql-client
repo_url: https://github.com/denisart/github-graphql-client
site_url: https://denisart.github.io/github-graphql-client/

nav:
    - Preparation: preparation.md
    - First query: first_query.md
    - Gql client: gql_client.md

plugins:
  - search